wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718176189
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 2
      - 23
      4: 3.11.9
      5: 0.17.1
      8:
      - 1
      - 5
      13: linux-x86_64
